"""new mirgrate after endpoints merge

Revision ID: 2e7bd706f707
Revises: 0a77ae6743b3
Create Date: 2024-04-19 01:58:52.254396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e7bd706f707'
down_revision: Union[str, None] = '0a77ae6743b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
