version: '3'

services:
  frontendui:
    build: frontendui
    ports:
      - 80:8501
    volumes:
      - './frontendui:/app'
    depends_on:
      - service
    
  service:
    build: service
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload 
    ports:
      - 8001:80
    volumes:
      - './service:/app'
    restart: always
    depends_on:
      - postgres



  postgres:
    image: postgres:14 #-alpine
    container_name: "postgres14"
    restart: always
    ports:
      - 5432:5432
    expose:
      - "5435"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    user: postgres
    environment:
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
       POSTGRES_DB: postgres