"""first migration

Revision ID: e25bfcbb1cf3
Revises: 
Create Date: 2024-04-25 22:03:05.147808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25bfcbb1cf3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbon_regulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regulation_name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_regulations_description'), 'carbon_regulations', ['description'], unique=False)
    op.create_index(op.f('ix_carbon_regulations_id'), 'carbon_regulations', ['id'], unique=False)
    op.create_index(op.f('ix_carbon_regulations_regulation_name'), 'carbon_regulations', ['regulation_name'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('c_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_c_name'), 'companies', ['c_name'], unique=False)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_table('carbon_offsets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('offset_type', sa.Enum('renewable_energy_projects', 'reforestation', name='offsettype'), nullable=True),
    sa.Column('offset_amount', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_offsets_date'), 'carbon_offsets', ['date'], unique=False)
    op.create_index(op.f('ix_carbon_offsets_id'), 'carbon_offsets', ['id'], unique=False)
    op.create_index(op.f('ix_carbon_offsets_offset_amount'), 'carbon_offsets', ['offset_amount'], unique=False)
    op.create_index(op.f('ix_carbon_offsets_offset_type'), 'carbon_offsets', ['offset_type'], unique=False)
    op.create_table('company_branches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('branch_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_branches_branch_name'), 'company_branches', ['branch_name'], unique=False)
    op.create_index(op.f('ix_company_branches_id'), 'company_branches', ['id'], unique=False)
    op.create_table('carbon_emissions_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('total_emission_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['company_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_emissions_sources_id'), 'carbon_emissions_sources', ['id'], unique=False)
    op.create_index(op.f('ix_carbon_emissions_sources_source_type'), 'carbon_emissions_sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_carbon_emissions_sources_total_emission_value'), 'carbon_emissions_sources', ['total_emission_value'], unique=False)
    op.create_table('carbon_footprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('footprint_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['carbon_emissions_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_footprints_footprint_value'), 'carbon_footprints', ['footprint_value'], unique=False)
    op.create_index(op.f('ix_carbon_footprints_id'), 'carbon_footprints', ['id'], unique=False)
    op.create_table('carbon_sequestration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('seq_value', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['carbon_emissions_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_carbon_sequestration_id'), 'carbon_sequestration', ['id'], unique=False)
    op.create_index(op.f('ix_carbon_sequestration_seq_value'), 'carbon_sequestration', ['seq_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_carbon_sequestration_seq_value'), table_name='carbon_sequestration')
    op.drop_index(op.f('ix_carbon_sequestration_id'), table_name='carbon_sequestration')
    op.drop_table('carbon_sequestration')
    op.drop_index(op.f('ix_carbon_footprints_id'), table_name='carbon_footprints')
    op.drop_index(op.f('ix_carbon_footprints_footprint_value'), table_name='carbon_footprints')
    op.drop_table('carbon_footprints')
    op.drop_index(op.f('ix_carbon_emissions_sources_total_emission_value'), table_name='carbon_emissions_sources')
    op.drop_index(op.f('ix_carbon_emissions_sources_source_type'), table_name='carbon_emissions_sources')
    op.drop_index(op.f('ix_carbon_emissions_sources_id'), table_name='carbon_emissions_sources')
    op.drop_table('carbon_emissions_sources')
    op.drop_index(op.f('ix_company_branches_id'), table_name='company_branches')
    op.drop_index(op.f('ix_company_branches_branch_name'), table_name='company_branches')
    op.drop_table('company_branches')
    op.drop_index(op.f('ix_carbon_offsets_offset_type'), table_name='carbon_offsets')
    op.drop_index(op.f('ix_carbon_offsets_offset_amount'), table_name='carbon_offsets')
    op.drop_index(op.f('ix_carbon_offsets_id'), table_name='carbon_offsets')
    op.drop_index(op.f('ix_carbon_offsets_date'), table_name='carbon_offsets')
    op.drop_table('carbon_offsets')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_c_name'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_carbon_regulations_regulation_name'), table_name='carbon_regulations')
    op.drop_index(op.f('ix_carbon_regulations_id'), table_name='carbon_regulations')
    op.drop_index(op.f('ix_carbon_regulations_description'), table_name='carbon_regulations')
    op.drop_table('carbon_regulations')
    # ### end Alembic commands ###
